<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>

    <parent>
        <groupId>cc.uncarbon.framework</groupId>
        <artifactId>helio-starters</artifactId>
        <version>2.5.0-SNAPSHOT</version>
    </parent>

    <groupId>cc.uncarbon.module</groupId>
    <artifactId>helio-boot-modular</artifactId>
    <description>Helio 多模块版单体脚手架</description>
    <version>${revision}</version>

    <properties>
        <!-- 当前工程内统一版本号 -->
        <revision>2.5.0-SNAPSHOT</revision>
        <!-- 如果实际开发使用的是JDK 21，则下面改成'21' -->
        <java.version>17</java.version>

        <!-- 这里管理全局第三方依赖版本，避免冲突 -->
        <!-- 统一版本号插件 -->
        <flatten-maven-plugin.version>1.7.0</flatten-maven-plugin.version>

        <!-- 文件上传 -->
        <x-file-storage.version>2.2.1</x-file-storage.version>
        <minio.version>8.5.17</minio.version>
    </properties>

    <modules>
        <module>bootstrap</module>
        <module>middleware/biz-common</module>
        <module>api/admin-api</module>
        <module>api/app-api</module>
        <module>service-module/sys</module>
        <module>service-module/oss</module>
    </modules>

    <dependencyManagement>
        <!-- 这里管理全局第三方依赖版本，避免冲突 -->
        <dependencies>
            <!-- 文件上传 -->
            <!-- 对象存储工具类 https://gitee.com/dromara/x-file-storage -->
            <dependency>
                <groupId>org.dromara.x-file-storage</groupId>
                <artifactId>x-file-storage-spring</artifactId>
                <version>${x-file-storage.version}</version>
                <exclusions>
                    <!-- hutool版本冲突，用 helio-core 的版本 -->
                    <exclusion>
                        <groupId>cn.hutool</groupId>
                        <artifactId>hutool-core</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- MinIO 依赖包 -->
            <dependency>
                <groupId>io.minio</groupId>
                <artifactId>minio</artifactId>
                <version>${minio.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <!-- 支持 mybatis XML 放置在 java 包下 -->
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>

        <plugins>
            <!-- 编译时，跳过单元测试 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>

            <!-- 编译时，不执行 mvn deploy -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <!-- 编译时，不生成 javadoc.jar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>

            <!-- 编译时，不生成 sources.jar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <configuration>
                    <skipSource>true</skipSource>
                </configuration>
            </plugin>

            <!-- 统一版本号，占位符 ${revision} -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <flattenMode>oss</flattenMode>
                    <updatePomFile>true</updatePomFile>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
