<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>

    <parent>
        <groupId>cc.uncarbon.module</groupId>
        <artifactId>helium-monolith</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>sys-service</artifactId>
    <description>
        系统管理服务
    </description>
    <version>${revision}</version>

    <properties>
        <tenant.version>${revision}</tenant.version>
    </properties>

    <dependencies>
        <!-- 实现契约 -->
        <dependency>
            <groupId>cc.uncarbon.module</groupId>
            <artifactId>sys-facade</artifactId>
            <version>${project.version}</version>
        </dependency>


        <!-- 引用其他契约 -->
        <dependency>
            <groupId>cc.uncarbon.module</groupId>
            <artifactId>commons</artifactId>
        </dependency>

        <dependency>
            <groupId>cc.uncarbon.module</groupId>
            <artifactId>tenant-facade</artifactId>
            <version>${tenant.version}</version>
        </dependency>


        <!-- 引用框架启动包 -->
        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helium-starter-db-mybatis-plus</artifactId>
        </dependency>

        <dependency>
            <groupId>cc.uncarbon.framework</groupId>
            <artifactId>helium-starter-db-dynamic-datasource</artifactId>
        </dependency>


        <!-- 引用其他第三方依赖 -->
        <!-- IP 地址归属地查询 -->
        <dependency>
            <groupId>org.lionsoul</groupId>
            <artifactId>ip2region</artifactId>
        </dependency>
    </dependencies>
</project>
